language: cpp
if: (type = push AND branch IN (master, develop)) OR (type = pull_request) OR (commit_message =~ .*\[run-ci\].*)
addons:
  apt:
    update: true
    packages:
      - libc++-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libx11-dev
      - libxi-dev
      - libgconf-2-4
      - libboost1.70-dev
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
cache:
  ccache: true
  directories:
  - build/linux-externals-release
  - build/windows-externals-release
jobs:
  include:
    - stage: test
      name: "Check Clang-Format"
      os: linux
      dist: bionic
      script: 
        - ./clang-format.sh
        - DIFF=$(git diff)
        - if [ ! -z "$DIFF" ]; then echo $DIFF && exit 1; fi
    - stage: build
      name: Linux GCC
      env: LABEL=LinuxGCC
      os: linux
      dist: bionic
      sudo: required
      before_script:
        - CC=gcc
        - CXX=g++
      script:
        - ./make_externals.sh -G "Unix Makefiles" -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
        - ./make.sh -G "Unix Makefiles" -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
    - name: Linux Clang
      env: LABEL=LinuxClang
      os: linux
      dist: bionic
      sudo: required
      before_script:
        - CC=clang
        - CXX=clang++
      script:
        - ./make_externals.sh -G "Unix Makefiles" -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
        - ./make.sh -G "Unix Makefiles" -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
    - name: Windows MSVC
      env: LABEL=WindowsMSVC
      os: windows
      script:
        - exit 1
        - # As windows builds take too long, we abort them for now
        - # cmd "/C make_externals.bat"
        - # cmd "/C make_release.bat"
  allow_failures:
    - os: windows
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ff52b66ca51dd75a045
    on_success: change
    on_failure: always
    on_start: never

